#!/usr/bin/php
<?php
if (php_sapi_name() !== 'cli') {
	echo "PHP-CLI not found!";
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Ahamed\Jext\Application;

$app = new Application();
$app->runCommand($argv);